apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb   # optional: choose NLB/ELB
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - port: 80        # external LB port
      targetPort: 3000
      protocol: TCP
